### ISSUE TITLE
Misc

### ISSUE THREAD

**Issue by admorris** [abmorris/BsphiKK#16]
# To-do list
## Plots
- [x] Angular efficiency of vetoes
- [ ] TIS acceptance fit projections in appendix
- [ ] Selection plots
- [ ] Model I and III fit projections in appendix
- [x] Prettier fit projections

## Tables
- [x] Results
- [x] Systematics
- [x] NLL and BIC fo 3 best models in text
- [x] NLL and BIC of all models in first 2 steps
- [ ] TIS acceptance fit results in appendix

## Text
- [x] Comment on moments
- [x] Comment on systematics
- [x] BsphiKK corrections
- [x] Conclusion
- [x] Appendix corrections
- [ ] Abstract
- [ ] Lay summary
- [ ] Minor corrections on all chapters
- [ ] Corrections on new bits
- [ ] Proof read

## Scripts
- [x] Extract results
- [x] 9 NLL distributions
